# This is a basic workflow to help you get started With Actions 

name: Docker Build and push 

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but onty for the master branch 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
# A workftow run is made up of One or more jobs that can run sequentiatly or in parallel 
jobs: 
  # This workflow contains a single job called "build" 
  build:
  # The type of runner that the job run on 
  runs—on: ubuntu—tatest

# Steps represent a sequence of tasks that be executed as part of the job 
steps:
  -
    name: Checkout
    uses: actions/checkout@v2
  -
    name: Set up QEMU
    uses: docker/setup-qemu-action@v1
  -
    name: Set up Docker Buitdx
    uses: docker/setup-buildx-action@v1
  - 
    name: Login to DockerHub
    uses: docker/login-action@v1
    with: 
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
  - 
    name: Build and push
    uses: docker/build-push-action@v2
    with:
      Context: .
      file: ./Dockerfile
      platforms: linux/amd64
      push: true
      tags: heckler64/python—helloworld:latest